import os
import shutil
import subprocess
import sys
import os

def sanitize_project_files(directory='.', auto_fix=False):
    """
    检查并修复项目中的 BOM 和 CRLF 问题。
    """
    extensions = ('.sty', '.cls', '.lua', '.tex', '.md', '.py', '.txt')
    exclude_dirs = {'.git', 'build', '__pycache__', '.vscode'}
    
    print("--- 正在检查文件编码与换行符 ---")
    
    for root, dirs, files in os.walk(directory):
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        
        for file in files:
            if file.endswith(extensions):
                filepath = os.path.join(root, file)
                
                with open(filepath, 'rb') as f:
                    content = f.read()
                
                has_bom = content.startswith(b'\xef\xbb\xbf')
                has_crlf = b'\r\n' in content
                
                if has_bom or has_crlf:
                    status = []
                    if has_bom: status.append("BOM")
                    if has_crlf: status.append("CRLF")
                    
                    print(f"发现问题 [{'/'.join(status)}]: {filepath}")
                    
                    if auto_fix:
                        # 执行修复：移除BOM并将CRLF替换为LF
                        new_content = content.replace(b'\xef\xbb\xbf', b'')
                        new_content = new_content.replace(b'\r\n', b'\n')
                        
                        with open(filepath, 'wb') as f:
                            f.write(new_content)
                        print(f"  [√] 已自动修复")

    print("--- 检查完成 ---\n")

def build_ctan_windows():
    print("Starting robust CTAN build for Windows...")
    sanitize_project_files(auto_fix=True)
    
    # 0. Tag version (update date and version in source files)
    print("Tagging version and updating dates...")
    try:
        subprocess.run(["texlua", "scripts/tag_version.lua"], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error: Version tagging failed: {e}")
        sys.exit(1)

    # 1. Run l3build ctan
    print("Running l3build ctan...")
    try:
        subprocess.run(["l3build", "ctan"], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Warning: l3build ctan returned exit code {e.returncode}. Proceeding with manual sync...")

    # 2. Identify the staging path
    # Usually build/distrib/ctan/luatex-cn
    staging_path = os.path.join("build", "distrib", "ctan", "luatex-cn")
    if not os.path.exists(staging_path):
        os.makedirs(staging_path, exist_ok=True)
    
    # 3. Robustly copy missing Chinese directories and src folder
    for folder in ["文档", "示例", "src"]:
        if os.path.exists(folder):
            dest = os.path.join(staging_path, folder)
            print(f"Syncing {folder} to {dest}...")
            if os.path.exists(dest):
                shutil.rmtree(dest)
            shutil.copytree(folder, dest)

    # 4. Clean up flattened source files at root
    print("Cleaning up flattened source files from root...")
    for ext in ["*.sty", "*.cls", "*.lua", "*.cfg"]:
        import glob
        for f in glob.glob(os.path.join(staging_path, ext)):
            try:
                os.remove(f)
            except:
                pass

    # 5. Run the post-process translation script
    print("Running path translation and reference updates...")
    try:
        subprocess.run(["python", "scripts/ctan_post_process.py", staging_path], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error: Post-processing failed: {e}")
        sys.exit(1)

    # 6. Clean up the useless zip generated by l3build
    ctan_root = os.path.dirname(staging_path)
    print(f"Cleaning up redundant zip files in {ctan_root}...")
    for f in os.listdir(ctan_root):
        if f.endswith(".zip"):
            os.remove(os.path.join(ctan_root, f))

    # 7. Create the final clean zip
    final_zip_base = os.path.join(ctan_root, "luatex-cn")
    print(f"Creating final CTAN package: {final_zip_base}.zip...")
    shutil.make_archive(final_zip_base, 'zip', ctan_root, "luatex-cn")

    print("\nCTAN Package successfully generated on Windows!")
    print(f"Staging area: {staging_path}")
    print(f"Final ZIP: {final_zip_base}.zip")

if __name__ == "__main__":
    build_ctan_windows()
